# This is a config for E2B sandbox template.
# You can use template ID (y9qclquiep0bk0ojsq3g) or template name (website_builder_template-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("website_builder_template-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("website_builder_template-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('website_builder_template-2')

team_id = "67b8a531-d116-47a4-9792-2fc56b5188e8"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "website_builder_template-2"
template_id = "y9qclquiep0bk0ojsq3g"
